
package efact.sgs.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExecutionException", targetNamespace = "http://service.sgs.efact/")
public class ExecutionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExecutionException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExecutionException_Exception(String message, ExecutionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExecutionException_Exception(String message, ExecutionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: efact.sgs.service.ExecutionException
     */
    public ExecutionException getFaultInfo() {
        return faultInfo;
    }

}
