
package efact.sgs.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionServiceImplService", targetNamespace = "http://service.sgs.efact/", wsdlLocation = "http://adapter.efact.pe/sgs/SgsTransactionServiced0aa6c5f1a934271b949881f123d6165?wsdl")
public class TransactionServiceImplService
    extends Service
{

    private final static URL TRANSACTIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRANSACTIONSERVICEIMPLSERVICE_QNAME = new QName("http://service.sgs.efact/", "TransactionServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://adapter.efact.pe/sgs/SgsTransactionServiced0aa6c5f1a934271b949881f123d6165?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRANSACTIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TransactionServiceImplService() {
        super(__getWsdlLocation(), TRANSACTIONSERVICEIMPLSERVICE_QNAME);
    }

    public TransactionServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public TransactionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONSERVICEIMPLSERVICE_QNAME);
    }

    public TransactionServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public TransactionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SgsTransactionService
     */
    @WebEndpoint(name = "TransactionServiceImplPort")
    public SgsTransactionService getTransactionServiceImplPort() {
        return super.getPort(new QName("http://service.sgs.efact/", "TransactionServiceImplPort"), SgsTransactionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SgsTransactionService
     */
    @WebEndpoint(name = "TransactionServiceImplPort")
    public SgsTransactionService getTransactionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sgs.efact/", "TransactionServiceImplPort"), SgsTransactionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRANSACTIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRANSACTIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
